#!/usr/bin/php
<?php

// Подключаем App из /app/Core/
require_once __DIR__ . '/app/Core/App.php';

Core\App::init(); // Инициализация

// Запуск консольного ядра
new Commands\ConsoleKernel()->handle($argv);
