#!/usr/bin/env php
<?php

use Core\App;
use Commands\ConsoleKernel;

require_once __DIR__ . '/Core/App.php';

// Инициализируем окружение (указываем путь к public)
App::init(__DIR__ . '/public');

// Запускаем консольное ядро
$kernel = new ConsoleKernel();
$kernel->handle($argv);
